apiVersion: v1
kind: Pod
metadata:
  name: {pod_name}
  labels:
    app: cluster-test
spec:
  nodeSelector:
    nodeType: clustertest
  restartPolicy: Never
  serviceAccountName: clustertest
  tolerations:
  - key: "clustertest"
    operator: "Exists"
    effect: "NoSchedule"
  containers:
  - name: main
    image: {image_repo}/diem/cluster_test:{cluster_test_image_tag}
    imagePullPolicy: Always
    env: [{env_variables}]
    command: [timeout, "{timeout_secs}", cluster-test, --deploy={image_tag} {extra_args}]
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values: ["cluster-test"]
        topologyKey: "kubernetes.io/hostname"
